print("Hello Akshay")
print("Hello from my pyCharm  ..")
print("25 September 2024 ..")
print("Hello Sayali, Love you ..")
print("Hello Sayali, Love you ..")
print("Hello Sayali, Love you ..")
print("Hello Sayali, Love you ..")