print("Hello Akshay")
print("Hello from my pyCharm  ..")
print("25 September 2024 ..")
print("This is how git worked ..")
print("Hello World from UBUNTU 24 ..")
print("this is one more line from linux ..")